import time
from os import system, name
import re
system("clear")
print(' AAAAA   U   U  TTTTT  OOOOO       EEEEE  X   X  EEEEE   CCCCC')
print('A     A  U   U    T    O   O       E       X X   E      C')
print('AAAAAAA  U   U    T    O   O       EEEE    XXX   EEEE   C')
print('A     A  U   U    T    O   O       E       X X   E      C')
print('A     A  UUUUU    T    OOOOO       EEEEE  X   X  EEEEE   CCCCC')
time.sleep(.75)
print('')
print('')
print('')
input('Press [ENTER] To Continue')
system('clear')
print('Instructions: when the file is created, run it by opening terminal and type in, python3 FILENAME.py')
time.sleep(5)
system('clear')
print('What will be the file name. DONT ADD FILE EXTENTION!')
filename = input('')
system('clear')
print('What will the terminal command be inside the auto executable.')
filetext = input('')
system('clear')
file_builder = open(filename+'.py', 'w+')
file_builder.write('from os import system, name\n')
file_builder.write("system("+"""'"""+filetext+"""')""")
file_builder.close()
system('clear')
print("Making file...")
time.sleep(.75)
system('clear')
print('File Created!')
time.sleep(.75)
print('')
print('')
input('Press [ENTER] to quit')
system('clear')
